# docker-compose.yml
version: "3"
services:
  app:
    container_name: task-api
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://task:jIuhlkVmdU@postgres:5432/task_db
      NODE_ENV: production
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres


  postgres:
    container_name: task-db
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: jIuhlkVmdU
      POSTGRES_DB: task_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task -d task_db"]
      interval: 1s
      timeout: 20s
      retries: 5