# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "npm", "run start:prod"]
    environment:
      DATABASE_URL: postgres://task:jIuhlkVmdU@localhost:5432/task_db
      NODE_ENV: production


  postgres:
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: jIuhlkVmdU
      POSTGRES_DB: task_db